apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  app: loadtest
fieldSpecs:
- kind: Service
  path: spec/selector
  create: true
- kind: Deployment
  path: spec/selector/matchLabels
  create: true
- kind: Deployment
  path: spec/template/metadata/labels
  create: true
