apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: eventing-test
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/kyma-project/eventing-tools
          name: publisher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-subscriber-0
  namespace: eventing-test
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/kyma-project/eventing-tools
          name: event-subscriber
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-subscriber-1
  namespace: eventing-test
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/kyma-project/eventing-tools
          name: event-subscriber
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-subscriber-2
  namespace: eventing-test
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/kyma-project/eventing-tools
          name: event-subscriber
---
